STRONGSORT:
  ECC: True              # activate camera motion compensation
  MC_LAMBDA: 0.995       # matching with both appearance (1 - MC_LAMBDA) and motion cost   0.995
  EMA_ALPHA: 0.9         # updates  appearance  state in  an exponential moving average manner   0.9
  MAX_DIST: 0.2          # The matching threshold. Samples with larger distance are considered an invalid match    0.2
  MAX_IOU_DISTANCE: 0.7  # Gating threshold. Associations with cost larger than this value are disregarded.    0.7
  MAX_AGE: 30            # Maximum number of missed misses before a track is deleted       30
  N_INIT: 3              # Number of frames that a track remains in initialization phase    3
  NN_BUDGET: 100         # Maximum size of the appearance descriptors gallery    100
  
